### ISSUE TITLE
problem in Inkscape 92.2

### ISSUE THREAD

**Issue by leoboke** [Daekkyn/inkscapeOptimizePath#1]
Hey there, 

FYI When I try to apply the optimize paths extension to a selected freehand line paths, it brings up a message box;

Traceback ( most recent call last );
File "optimizePaths.py, line 29, in <module> import networkx as nx
ImportError: No module named nertworx

**Comment by Daekkyn** [comment]
Hi, 

Yes, you need to install the NetworkX dependency: http://networkx.github.io
You can download the source code and copy the folder called "NetworkX" in the Inkscape extension folder.

**Comment by leoboke** [comment]
Thank you for the fast reply.  Now with NetworkX folder in the extensions folder, I am getting similar msg about "decorator" module.  Might be due to something I overlooked.
