### ISSUE TITLE
Problem with installing the script

### ISSUE THREAD

**Issue by patakk** [Daekkyn/inkscapeOptimizePath#2]
I am new to InkScape, but I've successfully _installed_ the AxiDraw software, by dragging all the files to the `/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkscapeOptimizePath` folder.
I've done the same with the files from this repository, but when I open InkScape, I can seem to find the script anywhere..

Any tips?

**Comment by marinopv** [comment]
Hi Patakk,

I have done the same as well as trying to put it into the "User extension" folder. Did you figure out how to install the scrip?

**Comment by Daekkyn** [comment]
I added installation instructions to the readme, have a look. You can then find the extension here: Extensions > Generate from Path > Optimize Path

**Comment by marinopv** [comment]
Thank you Daekkyn!

Now it works. Thanks a lot.

I am interested in running the script without inkscape. Is it hard to modify so that I could run it on a svg and feed it paths programmatically? Do you have tips on where to start?

**Comment by Daekkyn** [comment]
It should be fairly straightforward as there is no strong ties to Inkscape. The function parseSVG() should be adapted to read directly from a SVG file.

**Comment by marinopv** [comment]
OK perfect. Thank you for the tip. I am going to try it out :)
