### ISSUE TITLE
NodeView object is not an iterator.

### ISSUE THREAD

**Issue by patakk** [Daekkyn/inkscapeOptimizePath#3]
Hello, when try to run your code, I get the _NodeView object is not an iterator_ error message in the line 550, that looks like `v = next(g.nodes())`.

If I fix it to `v = g.nodes()[0]` it continues, but reports the same message in line 541. If I fix that, too, the next error message (line 555) says you can't make a set since dict is not hashable, and so on..

Any reasons why this is broken now?

Cheers

**Comment by Daekkyn** [comment]
Hi, 
NetworkX has broken their API compatibility at version 2.0: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

For now you can download 1.11: https://github.com/networkx/networkx/releases/tag/networkx-1.11

**Comment by Daekkyn** [comment]
Ok, fixed. Only works with NetworkX >= 2.0
